name: rank
description: A simple way to reorder a list or implement linked lists
version: 0.1.0
homepage: https://github.com/kedulu/rank

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
dev_dependencies:
  test: ^1.16.8