name: rank
description: A simple way to reorder a list or implement linked lists
version: 0.0.1
homepage: https://github.com/kedulu/rank

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartdoc: ^0.40.0
  _fe_analyzer_shared: ^19.0.0
  
dev_dependencies:
  pub_semver: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.16.8