name: rank
description: A list ordering system made in Dart that helps to implement a string index to reorder a list or implement linked lists.
version: 0.1.1
homepage: https://github.com/kedulu/rank

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8